version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             gunicorn --bind 0.0.0.0:8000 --workers 3 config.wsgi:application"
    environment:
      - DB_HOST=db
      - DB_NAME=db_stayreserve
      - DB_USER=kamileg
      - DB_PASS=kali2114
    depends_on:
      - db

  db:
    image: postgres:16.2-alpine3.19
    volumes:
      - dev-db-data:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=db_stayreserve
      - POSTGRES_USER=kamileg
      - POSTGRES_PASSWORD=kali2114


volumes:
  dev-db-data: