# Generated by Django 5.0.6 on 2024-06-02 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0002_property_delete_properties"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="is_reserved",
        ),
    ]
