# Generated by Django 5.0.6 on 2024-06-03 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservation",
            old_name="property",
            new_name="property_obj",
        ),
    ]
